on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: false

jobs:
  VisualStudio:
    runs-on: windows-latest
    name: MSVC-${{matrix.type}}
    strategy:
      matrix:
        type: ['shared', 'static']
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          python -m pip install meson ninja

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Sanity Checks
        run: |
          meson setup "${{github.workspace}}/build" -Ddefault_library=${{matrix.type}}
          meson compile -C "${{github.workspace}}/build" --verbose
